version: "3.1"

services:
  mysql:
    image: "mysql/mysql-server"
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    expose:
      - "3306"
  node:
    build: .
    restart: always
    ports:
      - "3065:3065"
    expose:
      - "3065"
    links:
      - mysql
    depends_on:
      - mysql
